version: '3'

networks:
  property-net:

services:
  # rabbitmq:
  #   image: rabbitmq:3.12.12-management-alpine
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   ports:
  #     - '5672:5672'
  #     - '15672:15672'
  #   networks:
  #     - property-net

  mongo:
    image: mongo:4.4.4
    environment:
      - MONGO_INITDB_DATABASE=nestjs_mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27018:27017'
    networks:
      - property-net
    # depends_on:
    #   - rabbitmq
    volumes:
      - ./mongo_data:/data/db

  # image: helloalf/microservice-property
  # property:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - MONGO_PORT=27017
  #     - MONGO_HOST=mongo
  #     - RABBITMQ_URI=amqp://3.135.210.254:5672
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mongo
  #   networks:
  #     - property-net
